#pragma once

#define DURATION_MILLISECOND 1L
#define DURATION_SECOND (1000 * DURATION_MILLISECOND)
#define DURATION_MINUTE (60 * DURATION_SECOND)
#define DURATION_HOUR (60 * DURATION_MINUTE)
#define DURATION_DAY (24 * DURATION_HOUR)
